// <auto-generated />
using AdatAccsesLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.Destination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KonaklamaSuresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.Property<double>("fiyat")
                        .HasColumnType("float");

                    b.Property<int>("kapasite")
                        .HasColumnType("int");

                    b.Property<string>("resimURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sehir")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("EntityLayer.Concrete.about", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aciklama2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.Property<string>("resimURL1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("abouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.about2", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("balik1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("balik2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resimURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("about2s");
                });

            modelBuilder.Entity("EntityLayer.Concrete.altHakkinda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("altHakkindas");
                });

            modelBuilder.Entity("EntityLayer.Concrete.iletisim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Harita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("iletisims");
                });

            modelBuilder.Entity("EntityLayer.Concrete.oneCikanlar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Post1Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Post1Baslıgı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Post1Durum")
                        .HasColumnType("bit");

                    b.Property<string>("Post1Image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("oneCikanlars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.onecikanlar2", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Post2Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Post2Baslıgı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Post2Durum")
                        .HasColumnType("bit");

                    b.Property<string>("Post2Image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("onecikanlar2s");
                });

            modelBuilder.Entity("EntityLayer.Concrete.referanslar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.Property<string>("müsteri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yorumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ımageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("referanslars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.reshberler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.Property<string>("twitterURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("reshberlers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.yeniHaberler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("yeniHaberlers");
                });
#pragma warning restore 612, 618
        }
    }
}
